blueprint:
  name: Link switch to schedule
  description: Turn on/off the switch based on the given schedule
  domain: automation
  input:
    target_switch:
      name: Target Switch
      description: The switch to be turned on/off based on the schedule
      selector:
        entity:
          filter:
            - domain: switch
    schedule_entity:
      name: Schedule
      description: The schedule to apply to the switch
      selector:
        entity:
          filter:
            - domain: schedule

triggers:
  - trigger: state
    entity_id: !input schedule_entity
conditions: []
actions:
  - if:
      - condition: state
        entity_id: !input schedule_entity
        state: "on"
    then:
      - action: switch.turn_on
        target:
          entity_id: !input target_switch
    else:
      - action: switch.turn_off
        target:
          entity_id: !input target_switch
mode: single
