blueprint:
  name: Link switch to schedule
  description: Turn on/off the switch based on the given schedule
  domain: automation
  input:
    target_switch:
      name: Target Switch
      description: The switch to be turned on/off based on the schedule
      selector:
        entity:
          filter:
            - domain: switch
    schedule_entity:
      name: Schedule
      description: The schedule to apply to the switch
      selector:
        entity:
          filter:
            - domain: schedule
    seasonal_control:
      name: Seasonal Control (Optional)
      description: Optional input_boolean to enable/disable the automation seasonally. Leave empty to always run.
      default: ""
      selector:
        entity:
          filter:
            - domain: input_boolean

triggers:
  - trigger: state
    entity_id: !input schedule_entity
conditions: []
variables:
  seasonal_control: !input seasonal_control
actions:
  - if:
      - condition: template
        value_template: "{{ seasonal_control == '' or states(seasonal_control) == 'on' }}"
    then:
      - if:
          - condition: state
            entity_id: !input schedule_entity
            state: "on"
        then:
          - action: switch.turn_on
            target:
              entity_id: !input target_switch
        else:
          - action: switch.turn_off
            target:
              entity_id: !input target_switch
mode: single
